
name: Compare GitHub vs Docker Tags 

on:
  workflow_call:
    inputs:
      repo_github:
        description: "Image Directory: "
        type: string
        required: true
      repo_docker:
        description: "Image Directory: "
        type: string
        required: true
    outputs:
      docker_version:
        value: ${{ jobs.github_vs_docker.outputs.docker_version }}
      repo_version:
        value: ${{ jobs.github_vs_docker.outputs.repo_version }}

jobs:
  github_vs_docker:
    runs-on: [ ubuntu-latest ]
    outputs:
      docker_version: ${{ steps.docker.outputs.docker_version }}
      repo_version: ${{ steps.repo.outputs.repo_version }}
    steps:
      - name: Get Latest Release
        run: echo "repo_version=$(curl -s 'https://api.github.com/repos/${{ inputs.repo_github }}/releases/latest'|jq -r .tag_name|sed 's/^v//')" >> $GITHUB_OUTPUT
        id: repo

      - name: Get GHCR Releases
        run: |
          GHCR_TOKEN=$(curl -s https://ghcr.io/token\?scope\="repository:${{ inputs.repo_docker }}:pull"|jq -r .token)
          curl -H 'Authorization: Bearer ${GHCR_TOKEN}' -s 'https://ghcr.io/v2/${{ inputs.repo_docker }}/tags/list'
        id: docker