name: Image Build Push

on:
  workflow_call:
    inputs:
      directory:
        description: "Image Directory: "
        type: string
        required: true
      image_name:
        description: "Image name: "
        type: string
        required: true
      image_version:
        description: "Image verion: "
        type: string
        required: true
      docker_owner:
        description: "Docker Org/Username : "
        type: string
        required: true  
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build_push:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/${{ inputs.directory }}
          platforms: linux/amd64 #,linux/arm/v7 # Disable ARM
          tags: |
            ${{ inputs.docker_owner }}/${{ inputs.image_name }}:${{ inputs.image_version }}
            ${{ inputs.docker_owner }}/${{ inputs.image_name }}:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: IMG_VERSION=${{ inputs.image_version }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max